### ISSUE TITLE
Progress dialog appearing with white background in lollipop

### ISSUE THREAD

**Issue by aviotron** [ttasterisco/CustomProgressDialogExample#1]
The dialog works fine with kitkat. But with lollipop it comes with the default white background.

**Comment by ttasterisco** [comment]
Thanks, I'll take a look into it once I have some free time.

**Comment by aviotron** [comment]
Well, I got the solution.
We just have to add 
getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));
before setContentView().
